$bg_h = rgb(1d2021)
$bg_h_alpha = 1d2021

$bg = rgb(282828)
$bg_alpha = 282828

$bg_s = rgb(32302f)
$bg_s_alpha = 32302f

$bg1 = rgb(3c3836)
$bg1_alpha = 3c3836

$bg2 = rgb(504945)
$bg2_alpha = 504945

$bg3 = rgb(665c54)
$bg3_alpha = 665c54

$bg4 = rgb(7c6f64)
$bg4_alpha = 7c6f64


$fg = rgb(fbf1c7)
$fg_alpha = fbf1c7

$fg1 = rgb(ebdbb2)
$fg1_alpha = ebdbb2

$fg2 = rgb(d5c4a1)
$fg2_alpha = d5c4a1

$fg3 = rgb(bdae93)
$fg3_alpha = bdae93

$fg4 = rgb(a89984)
$fg4_alpha = a89984


$red = rgb(fb4934)
$red_alpha = fb4934

$green = rgb(b8bb26)
$green_alpha = b8bb26

$yellow = rgb(fabd2f)
$yellow_alpha = fabd2f

$blue = rgb(83a598)
$blue_alpha = 83a598

$purple = rgb(d3869b)
$purple_alpha = d3869b

$aqua = rgb(8ec07c)
$aqua_alpha = 8ec07c

$gray = rgb(928374)
$gray_alpha = 928374

$orange = rgb(fe8019)
$orange_alpha = fe8019


$red_dim = rgb(cc2412)
$red_dim_alpha = cc2412

$green_dim = rgb(98971a)
$green_dim_alpha = 98971a

$yellow_dim = rgb(d79921)
$yellow_dim_alpha = d79921

$blue_dim = rgb(458588)
$blue_dim_alpha = 458588

$purple_dim = rgb(b16286)
$purple_dim_alpha = b16286

$aqua_dim = rgb(689d6a)
$aqua_dim_alpha = 689d6a

$gray_dim = rgb(a89984)
$gray_dim_alpha = a89984

$orange_dim = rgb(d65d0e)
$orange_dim_alpha = d65d0e
